import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bbc9cf",
        background: "#131313",
        "on-background": "#e5e2e1",
        outline: "#859399",
        "outline-variant": "#3c494e",
        primary: "#a5e7ff",
        "primary-container": "#00d2ff",
        "primary-fixed": "#b6ebff",
        "primary-fixed-dim": "#47d6ff",
        "on-primary": "#003543",
        "on-primary-container": "#00566a",
        "on-primary-fixed": "#001f28",
        "on-primary-fixed-variant": "#004e60",
        secondary: "#d9b9ff",
        "secondary-container": "#6c04ca",
        "secondary-fixed": "#eedcff",
        "secondary-fixed-dim": "#d9b9ff",
        "on-secondary": "#450086",
        "on-secondary-container": "#d3b0ff",
        "on-secondary-fixed": "#2a0054",
        "on-secondary-fixed-variant": "#6300bb",
        tertiary: "#dcdddf",
        "tertiary-container": "#c0c1c3",
        "tertiary-fixed": "#e2e2e4",
        "tertiary-fixed-dim": "#c6c6c8",
        "on-tertiary": "#2f3132",
        "on-tertiary-container": "#4d4f51",
        "on-tertiary-fixed": "#1a1c1d",
        "on-tertiary-fixed-variant": "#454749",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
        "container-padding": "24px",
        "section-gap": "160px",
        "section-gap-mobile": "80px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      boxShadow: {
        glass: "inset 0 1px 0 rgba(255,255,255,0.08)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        wave: "wave 1.2s ease-in-out infinite",
        "pulse-soft": "pulseSoft 2.2s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        wave: {
          "0%, 100%": { height: "8px", opacity: "0.45" },
          "50%": { height: "30px", opacity: "1" },
        },
        pulseSoft: {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.15)", opacity: ".45" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
